### ISSUE TITLE
DOCKER [ERR ] Error Creating Directory

### ISSUE THREAD

**Issue by morganzero** [varbhat/exatorrent#22]
Hi,
I just built exatorrent in docker container following your guide. However, I stumbled upon this issue in container logs as the app won't start.

Any ideas as to why I'm getting this issue? am I or your image in lack of proper permissions to create the directory?
```
Address => :5000
Directory => exadir
[ERR ] 2021/08/27 23:15:00 Error Creating Directory
```

Here is my compose:
```yml
version: '3.8'

services:
  exatorrent:
    container_name: exatorrent
    image: ghcr.io/varbhat/exatorrent:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
      - '42069:42069'
      - '42069:42069/udp'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/appdata/exatorrent:/exa/exadir'
      - '/mnt:/mnt'
```
