### ISSUE TITLE
After adding a magnet link to the docker version, the system hangs

### ISSUE THREAD

**Issue by ystyle** [varbhat/exatorrent#41]
docker-compose.yaml
```yaml
version: '3.1'

services:
  torrent:
    image: ghcr.io/varbhat/exatorrent:latest
    restart: always
    volumes:
      - ${HOME}/Downloads:/exa/exadir
    ports:
      - 5000:5000
      - 42069:42069
```
```shell
docker-compose up -d
```
operation:
1. add a new admin user
2. logout and login new user  and disabled adminuser
3. add magnet link

magnet link： 
```
magnet:?xt=urn:btih:787b951c9635c58928260e02a01e2b5434d8bb13&tr=http://tracker.36dm.com:2710/announce
```

system info:
```shell
                   -`                    ystyle@Archlinux 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: XPS 13 7390 
               `+oooooo:                 Kernel: 5.13.12-arch1-1 
               -+oooooo+:                Uptime: 7 days, 4 hours, 18 mins 
             `/:-:++oooo+:               Packages: 1627 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.22.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: Breeze 
       -osssssso.      :ssssssso.        Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
      :osssssss/        osssso+++.       Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: terminator 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-10710U (12) @ 4.700GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Comet Lake UHD Graphics 
 `++:.                           `-/+/   Memory: 7627MiB / 15695MiB 
 .`                                 `/
```

```
 ystyle@Archlinux ~/Downloads  id
uid=1000(ystyle) gid=1000(ystyle) groups=1000(ystyle),972(docker),998(wheel)
```

cpu: 200%(total 600%) Memory: 100% (16g ram and 20G swap)
